### ISSUE TITLE
"Out of memory" error on broken mailbox

### ISSUE THREAD

**Issue by dune73** [vandry/mairix#20]
I'm getting an out of memory error on a mailbox that mutt messed up. I searched for an hour to identify the message
that causes the bug and then I condensed it to the attached file test-mailbox that triggers the error below (unzip the file of course).

This is on a fresh compilation from github HEAD.

```
$ rm /tmp/mairix.database.*; mairix -v -F -p -f /tmp/.mairixrc 2>&1 
mairix DEVELOPMENT, Copyright (C) 2002-2010 Richard P. Curnow
mairix comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the GNU General Public License for details.

Finding all currently existing messages...
Reading existing database...
Checking message path integrity
Checking to
Checking cc
Checking from
Checking subject
Checking body
Checking attachment_name
Loaded 1 existing messages
Scanning mbox /tmp/test-mailbox : 100% done
1 newly dead messages, 1 messages now dead in total
Out of memory (at rfc822.c:465, -203 bytes)
```

[test-mailbox.zip](https://github.com/vandry/mairix/files/5910185/test-mailbox.zip)

**Comment by vandry** [comment]
Thank you for putting together such a reproducible test case!

**Comment by dune73** [comment]
Thank you for your prompt fix. Putting together a useful test case was the least I could do given mairix is such a big help for me.
