### ISSUE TITLE
Index "BCC" headers

### ISSUE THREAD

**Issue by ericpruitt** [vandry/mairix#9]
I think "BCC" email headers should be explicitly indexed. I can't think of any major email service providers or user agents that don't allow users to BCC recipients. I propose using "B:" as the search pattern prefix and modifying the "a:" so that it also implies "B:".

**Comment by vandry** [comment]
SGTM. Of course it will only ever work in "Sent" and similar folders, as messages being delivered in never have Bcc: headers.
